-- MySQL Script generated by MySQL Workbench
-- Thu Oct 17 15:36:50 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Course` (
  `number` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `credits` INT NULL,
  `syllabus` VARCHAR(45) NULL,
  `prerequisites` VARCHAR(45) NULL,
  PRIMARY KEY (`number`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`course_offering`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`course_offering` (
  `course_number` INT NOT NULL,
  `year` INT NULL,
  `semester` INT NULL,
  `section_number` INT NULL,
  `instructor_id` INT NULL,
  `timing` VARCHAR(45) NULL,
  `classroom` VARCHAR(45) NULL,
  PRIMARY KEY (`course_number`),
  CONSTRAINT `number`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Course` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`students` (
  `student_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `program` VARCHAR(45) NULL,
  PRIMARY KEY (`student_id`),
  CONSTRAINT `semester`
    FOREIGN KEY ()
    REFERENCES `mydb`.`course_offering` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`instructors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`instructors` (
  `identification_number` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `department` VARCHAR(45) NULL,
  `title` VARCHAR(45) NULL,
  PRIMARY KEY (`identification_number`),
  CONSTRAINT `instructor_id`
    FOREIGN KEY ()
    REFERENCES `mydb`.`course_offering` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
