-- MySQL Script generated by MySQL Workbench
-- Thu Oct 17 15:37:15 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`course` (
  `number` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `credits` INT NULL,
  `syllabus` VARCHAR(45) NULL,
  `prerequesties` VARCHAR(45) NULL,
  PRIMARY KEY (`number`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`instuctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`instuctor` (
  `instuctor_id` INT NOT NULL,
  `name_inst` VARCHAR(45) NULL,
  `dep` VARCHAR(45) NULL,
  `title_inst` VARCHAR(45) NULL,
  PRIMARY KEY (`instuctor_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`course_offereing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`course_offereing` (
  `course_number` INT NOT NULL,
  `year` INT NULL,
  `sem` INT NULL,
  `sec_no` INT NULL,
  `instructor_id` INT NULL,
  `timing` VARCHAR(45) NULL,
  `classroom` INT NULL,
  PRIMARY KEY (`course_number`),
  INDEX `instructor_id_idx` (`instructor_id` ASC) VISIBLE,
  CONSTRAINT `number`
    FOREIGN KEY (`course_number`)
    REFERENCES `mydb`.`course` (`number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `instructor_id`
    FOREIGN KEY (`instructor_id`)
    REFERENCES `mydb`.`instuctor` (`instuctor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`students` (
  `student_id` INT NOT NULL,
  `name_st` VARCHAR(45) NULL,
  `program` VARCHAR(45) NULL,
  PRIMARY KEY (`student_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
